### ISSUE TITLE
Flow variable used before defined

### ISSUE THREAD

**Issue by Zoramite** [grow/webreview-client#5]
From https://github.com/grow/grow/issues/738:

```
Traceback (most recent call last):
  File "grow", line 58, in <module>
  File "site-packages/click/core.py", line 722, in __call__
  File "site-packages/click/core.py", line 697, in main
  File "site-packages/click/core.py", line 1066, in invoke
  File "site-packages/click/core.py", line 895, in invoke
  File "site-packages/click/core.py", line 535, in invoke
  File "site-packages/click/decorators.py", line 17, in new_func
  File "grow/commands/subcommands/stage.py", line 66, in stage
  File "grow/deployments/destinations/webreview_destination.py", line 105, in deploy
  File "grow/deployments/destinations/base.py", line 279, in deploy
  File "grow/deployments/destinations/base.py", line 163, in _get_remote_index
  File "grow/deployments/destinations/base.py", line 232, in read_control_file
  File "grow/deployments/destinations/webreview_destination.py", line 133, in read_file
  File "site-packages/webreview/webreview.py", line 300, in read
  File "site-packages/webreview/webreview.py", line 277, in get_signed_requests
  File "site-packages/webreview/webreview.py", line 182, in get_service
  File "site-packages/webreview/webreview.py", line 229, in get_credentials
UnboundLocalError: local variable 'flow' referenced before assignment
[15504] Failed to execute script grow
```

**Comment by Haugen** [comment]
I get this exact error when trying to run `grow stage` using Webreview. I'm on Grow 0.7.6 which install Webreview 0.1.1. I have tried using the `--clear-auth` option, like `grow stage --subdomain=haugen --clear-auth`, but no matter how I use `--clear-auth` I get the response `Error: No such command "clear-auth"`.

I've also tried using `grow --auth [email]` and `grow --interactive-auth`, but both return `Error: Missing command.`

I'm an admin in the Webreview project I'm trying to stage to, and I've reinstalled Grow, but still the same issue. Any ideas on how to get this cleared up?

**UPDATE**: Thanks to [jeremydw's answer in another issue](https://github.com/grow/grow/issues/201#issuecomment-212515343) I finally managed to get it to work running `grow --clear-auth stage --subdomain=haugen`

**Comment by jeremydw** [comment]
This should have been fixed back in https://github.com/grow/webreview-client/commit/7febc50b3390e1dfdeca8a8f951731c52c801474

Updating Grow should resolve the issue. If you can't update to Grow 1x for whatever reason, try updating to Grow `0.8.27` which is the latest version of the Python 2x version of Grow. Thanks!
